var LANGPACK = {
    "en": {
        'Home': 'Home',
        'title_intro': 'We focus on mobile, web, and B2B software development.',
        'Experienced_intro': 'All of our engineers and designers have many years work experience in their fields. (mobile, web, big data, and UX, etc.)',
        'Maintainable_intro': 'We truly know you are afraid of the mess code built by outsourcing? We, either. We write the clean code and do good documentations.',
        'Agile_intro': 'We split the projects into several sprints, you will get the demos mostly every 2 weeks. We also deliver phone and to door support for you.',
    },

    "zh_TW": {
        'Home': '首頁',
        'About': '關於',
        'Portfolio': '作品',
        'Contact': '聯繫我們',
        'Welcome to plusDiff':'歡迎, 這裡是 plusDiff',
        'title_intro': '我們專注於智慧型手機、網站、和 B2B 模式的軟體開發',
        'Experienced': '經驗豐富',
        'Experienced_intro': '我們的工程師與設計師皆擁有多年開發經驗, 無論是在智慧型手機、網站、大資料及使用者體驗上。',
        'Maintainable': '易維護',
        'Maintainable_intro': '我們知道您害怕外包的程式讓人難以維護, 我們熟悉物件導向與設計模式, 乾淨的程式碼與好的註解文件讓您不用再擔心後續維護的問題。',
        'Agile': '敏捷開發',
        'Agile_intro': '我們採用敏捷開發, 專案開發前會制訂展示日期, 大約每兩個星期就會讓您了解最新開發情況, 避免最後一刻耽誤您寶貴的時間。',
        'plusDiff delivers good quility softwares and wonderful creativity!': 'plusDiff 所製作的軟體具有高品質、很棒的創造力!',
        'Our Team': '我們的團隊',
        'We love fun and crazy things, meet us and join us.': '我們熱愛有趣和瘋狂的玩意, 認識和加入我們吧',
        'you may find something interesting in this showcase room': '您或許可以在這個展示間裡找到一些有趣的東西',
        'Work hard, play harder': '努力工作, 更盡情地玩',
        'in plusDiff': '在 plusDiff',
        'All': '全部',
        'Mobile': '智慧型手機',
        'Web': '網站',
        'UX': '使用者體驗',
        'Hack Everything!': '大膽地改變世界!',
        'Contact us': '聯繫我們',
        'If you are interested in our products (services), or any questions, please feel free to contact us.': '如果您對我們的產品或服務有興趣, 或是您有任何問題, 竭誠歡迎您立刻與我們聯繫。',
        'Your Name': '您的姓名',
        'Your Email': '您的電子郵件',
        'Subject': '主旨',
        'Message': '訊息',
        'SEND MESSAGE': '送出訊息',
        'Copyright': '版權所有',
    }
}
